name: PHP

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        laravel-version: ['^6.0', '^7.0', '^8.0', '^9.0']
        php-versions: ['7.3', '7.4', '8.0']
        exclude:
          - laravel-version: ^6.0
            php-version: 8.0
          - laravel-version: ^7.0
            php-version: 8.0
          - laravel-version: ^9.0
            php-version: 7.4
    name: PHP ${{ matrix.php-versions }} on ${{ matrix.laravel-version }}
    steps:
    - name: db
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'blockings-testing' # Optional, default value is "test". The specified database which will be create
        mysql user: 'developer' # Required if "mysql root password" is empty, default is empty
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, xdebug
        coverage: xdebug
    - name: Install dependencies
      run: |
        composer require --no-update --no-interaction "illuminate/support:${{ matrix.laravel-version }}" satooshi/php-coveralls
        composer update --no-interaction --prefer-dist --no-suggest
    - name: Lint composer.json
      run: composer validate
    - name: Run Tests
      run: composer test:ci
    - name: Upload Coverage
      run: bash <(curl -s https://codecov.io/bash)
